module Jazz.Compiler.Bootstrap.TypedCoreExpressionDirectCallFixtures
  ( Fixture (..),
    fixtureNames,
    acceptedFixtureNames,
    rejectedFixtureNames,
    priorScalarDirectCallFixtureNames,
    fixtures,
    expectedUnitProgram,
    scalarExpectedLoweredPrograms,
    explicitNumericScalarLoweringPrograms,
    fullUInt64ScalarLoweringPrograms,
    nestedScalarTypedProgram,
    expectedNestedScalarLoweredProgram,
    scalarFixtures,
    scalarExpectedPrograms,
    scalarPatternCaseExpectedPrograms,
    scalarPatternCaseExpectedLoweredPrograms,
    scalarPatternCaseAnalysisExpectedPrograms,
    scalarPatternCaseLowererBoundaryPrograms,
    scalarBindingExpectedPrograms,
    scalarBindingExpectedLoweredPrograms,
    managedTextProducerFixtures,
    managedTextExpectedPrograms,
    managedTextOperationProducerFixtures,
    managedTextOperationExpectedPrograms,
    managedTextOperationExpectedLoweredPrograms,
    managedTextKernelBoundaryFixtures,
    managedTextExclusionFixtures,
    managedTextExpectedLoweredPrograms,
    managedProductVariantFixtures,
    managedProductVariantFixture,
    lowererBoundaryExpectedLoweredPrograms,
    lexicalCaptureExpectedPrograms,
    lexicalCaptureExpectedLoweredPrograms,
    curriedApplicationExpectedPrograms,
    curriedApplicationExpectedLoweredPrograms,
    directCallExpectedPrograms,
    directRecursionExpectedPrograms,
    directRecursionExpectedLoweredPrograms,
    closureRecursionExpectedPrograms,
    closureRecursionExpectedLoweredPrograms,
    closedCallableExpectedPrograms,
    directCallExpectedLoweredPrograms,
    closedCallableExpectedLoweredPrograms,
    independentClosureExpectedLoweredPrograms,
    functionBodyConsumedCallExpectedProgram,
    functionBodyPartialApplicationExpectedProgram,
    nestedTailControlFlowExpectedLoweredPrograms,
    rfcClosureEnvironmentIdentityProgram,
    lowererBoundaryPrograms,
    validIndependentLowererPrograms,
    invalidLowererBoundaryPrograms,
    independentLowererPrograms,
    lowererStructuralBoundaryPrograms,
    reviewLowererBoundaryPrograms,
    producerEdgeFixtures,
    scalarBindingProducerFixtures,
    ordinaryForwardVisibilityFixture,
    forwardVisibilityNegativeFixtures,
    rejectedScalarFixtures,
    resolveFixture,
    resolveFixtureWithLookup,
    explicitNumericTypes,
  )
where

import Jazz.Compiler.Bootstrap.TypedCoreExpressionDirectCallFixtures.CallsCaptures
import Jazz.Compiler.Bootstrap.TypedCoreExpressionDirectCallFixtures.LowererBoundary
import Jazz.Compiler.Bootstrap.TypedCoreExpressionDirectCallFixtures.ManagedProductsVariants
import Jazz.Compiler.Bootstrap.TypedCoreExpressionDirectCallFixtures.ManagedText
import Jazz.Compiler.Bootstrap.TypedCoreExpressionDirectCallFixtures.Scalar
import Jazz.Compiler.Bootstrap.TypedCoreExpressionDirectCallFixtures.Source
