{-# LANGUAGE OverloadedStrings #-}

module Main (main) where

import Jazz.Compiler.Bootstrap.TypedCoreExpressionDirectCallSpec.BoundaryTests
import Jazz.Compiler.Bootstrap.TypedCoreExpressionDirectCallSpec.CallTests
import Jazz.Compiler.Bootstrap.TypedCoreExpressionDirectCallSpec.CaptureRecursionTests
import Jazz.Compiler.Bootstrap.TypedCoreExpressionDirectCallSpec.ManagedProductsVariantsTests
import Jazz.Compiler.Bootstrap.TypedCoreExpressionDirectCallSpec.ManifestTests
import Jazz.Compiler.Bootstrap.TypedCoreExpressionDirectCallSpec.ScalarTextTests
import Jazz.TestHarness (NamedTest, runTestSuite)

main :: IO ()
main = runTestSuite "TypedCoreExpressionDirectCall" tests

tests :: [NamedTest]
tests =
  [ ("audits the complete producer fixture manifest", testFixtureManifest),
    ("audits the independent typed-core lowerer manifests", testIndependentLowererManifest),
    ("audits every producer failure kind used by the rejected manifest", testRejectedManifestProducerFailures),
    ("runs every accepted manifest fixture through its current opt-in boundary", testAcceptedManifestPipeline),
    ("keeps function-body consumed calls as ordinary operations", testFunctionResultNegativeTerminators),
    ("preserves function-body partial-application returns", testFunctionBodyPartialApplicationResult),
    ("lowers nested function-result control flow exactly", testNestedTailControlFlow),
    ("produces exact scalar pattern cases before lowering", testScalarPatternCaseProduction),
    ("rechecks the scalar pattern-case lowerer profile", testScalarPatternCaseLowererBoundary),
    ("rejects scalar pattern cases outside the bounded producer profile", testScalarPatternCaseProducerBoundaries),
    ("retains scalar pattern-case arm positions after pattern typing failures", testScalarPatternCaseArmResultPositions),
    ("preserves pattern-case captures and closure-valued arm profiles", testScalarPatternCaseAnalysisProduction),
    ("transports nested and in-flight scalar pattern-case values", testScalarPatternCaseTransportLowering),
    ("produces and lowers conditional profile combinations", testConditionalProfileCoverage),
    ("retains managed tuple and local-data structure once", testManagedProductVariantRetention),
    ("produces exact managed product and local-variant artifacts", testManagedProductVariantProduction),
    ("catalogs deterministic managed product and variant layouts", testManagedProductVariantLayoutCatalog),
    ("lowers exact managed product and local-variant construction", testManagedProductVariantLowering),
    ("keeps arbitrary managed construction failures at the lowerer boundary", testManagedConstructionLowererBoundaries),
    ("produces concrete scalar bindings in source order", testScalarBindingProduction),
    ("produces managed Text literals and bindings exactly", testManagedTextProduction),
    ("produces exact managed Text operations", testManagedTextOperationProduction),
    ("lowers exact managed Text runtime services", testManagedTextOperationLowering),
    ("keeps managed Text kernel values and arities bounded", testManagedTextKernelBoundaries),
    ("locks every managed Text profile exclusion", testManagedTextProfileExclusions),
    ("leaves managed Text service integrity with Lowered IR validation", testManagedTextServiceValidationOwnership),
    ("lowers managed Text literals with one layout and no services", testManagedTextLowering),
    ("produces binder-resolved lexical closures", testLexicalCaptureProduction),
    ("produces staged curried partial applications", testCurriedApplicationProduction),
    ("lowers staged curried applications", testCurriedApplicationLowering),
    ("keeps non-callable oversaturation at the source diagnostic boundary", testNonCallableOversaturationDiagnostic),
    ("lowers lexical closures with exact environments", testLexicalCaptureLowering),
    ("supports the complete lexical capture fixture matrix", testLexicalCaptureFixtureMatrix),
    ("dispatches captured closure callees from nested named closures", testClosureCaptureReviewRegression "named-nested-captured-closure-call"),
    ("propagates transitive named closure environments", testClosureCaptureReviewRegression "transitive-named-closure-capture"),
    ("preserves lifted lambda failure preorder", testLiftedLambdaFailurePreorder),
    ("rejects lifted lambda aliases for module metadata", testLiftedLambdaMetadataAlias),
    ("lowers scalar bindings once for ordered entry reuse", testScalarBindingLowering),
    ("preserves flattened recipes through a named direct leading-lambda chain", testThreeArgumentDirectLeadingLambdaRecipe),
    ("retains every explicit numeric width while lowering", testExplicitNumericWidthLowering),
    ("lowers the full valid UInt64 domain twice", testFullUInt64Lowering),
    ("lowers nested scalar operands from left to right", testNestedScalarLowering),
    ("validates typed core before checking the lowering profile", testLoweringPrecedence),
    ("uses the exact RFC closure environment identity grammar", testRfcClosureEnvironmentIdentity),
    ("lowers every independent unary closure boundary twice", testSupportedClosureLowererBoundary),
    ("rechecks every callable restriction on arbitrary valid typed programs", testLowererCallableBoundary),
    ("rejects malformed callable recipes and binder references before lowering", testInvalidLowererTypedCoreBoundary),
    ("rechecks lowerer-only structural boundaries on arbitrary valid typed programs", testLowererStructuralBoundary),
    ("keeps forward visibility inside the typed-core production profile", testForwardVisibilityBoundary),
    ("admits concrete unit-typed forward functions", testUnitForwardVisibility),
    ("admits captured arguments inside direct-call bodies", testCurriedArgumentCapture),
    ("retains supplied arguments inside partial applications", testPartialApplicationArgumentCapture),
    ("retains supplied argument failures when non-local calls are rejected", testNonLocalCallArgumentFailureAccumulation),
    ("retains later sibling failures after accepting a captured closure call", testClosureUseArgumentFailureOrder),
    ("collapses mixed callable-use reasons to one closure classification", testClosureShapeClassificationCollapse),
    ("specializes integer literals to direct-call parameter types", testNarrowLiteralDirectCall),
    ("specializes computed integer results to declared return types", testNarrowCompositeFunctionResult),
    ("specializes comparison operands to their unified numeric type", testNarrowComparisonOperand),
    ("specializes terminal binary operands to their unified numeric type", testNarrowRootBinaryDirectCall),
    ("normalizes equivalent scalar aliases to the expected type", testEquivalentScalarAliasSpecialization),
    ("rejects inherited recursive captures unavailable at an earlier caller", testEarlierCallerTransitiveCaptureAvailability),
    ("specializes every use of a captured numeric scalar", testCapturedNumericScalarReferenceSpecialization),
    ("specializes enclosing expressions that reuse captured numeric scalars", testCapturedCompositeScalarSpecialization),
    ("specializes independent scalar binders recolored with recursive captures", testCapturedCompositeScalarBinderSpecialization),
    ("preserves capture expectations for non-integral comparison operands", testCapturedComparisonResultSpecialization),
    ("specializes enclosing function expressions that reuse captured numeric scalars", testCapturedFunctionBodySpecialization),
    ("specializes callable parameters recolored with captured numeric scalars", testCapturedFunctionParameterSpecialization),
    ("specializes callable parameters invoked with captured numeric scalars", testCapturedCallableParameterApplicationSpecialization),
    ("specializes scalar binders recolored inside callable bodies", testCapturedFunctionScalarBinderSpecialization),
    ("specializes scalar binders recolored as callable arguments", testCapturedFunctionArgumentScalarBinderSpecialization),
    ("specializes scalar binders initialized from callable results", testCapturedFunctionResultScalarBinderSpecialization),
    ("specializes higher-order profiles from callable arguments", testCapturedHigherOrderCallableArgumentSpecialization),
    ("specializes forwarded higher-order profiles from callable arguments", testCapturedForwardedHigherOrderCallableArgumentSpecialization),
    ("specializes terminal anonymous callable bodies", testCapturedTerminalAnonymousCallableSpecialization),
    ("respecializes callers of specialized named functions", testCapturedNamedCallerSpecialization),
    ("specializes scalar alias sources captured by recursive closures", testCapturedScalarAliasSourceSpecialization),
    ("specializes recursive scalar alias captures across omitted source statements", testRecordedScalarStatementIndices),
    ("rejects eager recursive closure calls before their captures exist", testEagerRecursiveClosureCaptureAvailability),
    ("rejects eager nested closure construction before transitive captures exist", testEagerNestedClosureCaptureAvailability),
    ("rejects unused user-defined operator bindings", testUnusedUserDefinedOperatorBinding),
    ("retains root data failures with their real statement paths", testRootDataFailureAccumulation),
    ("retains nested data-block child failures in structural order", testNestedDataFailureAccumulation),
    ("accepts anonymous lambdas as module results", testAnonymousLambdaResultAcceptance),
    ("keeps invalid signed forward declarations visible to analysis", testInvalidForwardDeclarationAnalysisVisibility),
    ("preserves ordinary diagnostics while producing typed core", testProductionDiagnosticCompatibility),
    ("rejects class and impl declarations from the scalar direct-call profile", testUnsupportedDeclarationProfile),
    ("retains impl method body profile failures", testImplMethodBodyFailureAccumulation),
    ("retains unsupported binding markers with initializer failures", testUnsupportedBindingFailureAccumulation),
    ("preserves qualified-method application inference in rejected profiles", testQualifiedMethodInferenceCompatibility),
    ("rejects uncommitted integer ranges outside Int64", testOutOfRangeDefaultIntegerRejection),
    ("rejects numeric promotions that typed core cannot represent", testNumericPromotionRejection),
    ("rejects the complete callable profile twice", testRejectedCallableProfile),
    ("reports rejected scalar profile nodes twice", testRejectedScalarProfile),
    ("rejects modules without an executable result twice", testMissingModuleResultProduction),
    ("retains statement failures when the module result is missing", testMissingResultFailureAccumulation),
    ("ranks module failures before statement failures in authored export order", testModuleFailureOrder),
    ("keeps exported callable-info failures statement-owned and unique", testExportedCallableFailureOwnership),
    ("retains unsupported compound child failures in structural order", testCompoundFailureAccumulation),
    ("retains every unsupported composite child failure in structural order", testUnsupportedCompositeFailureAccumulation),
    ("rejects ambiguous producer binder identities twice", testProducerIdentityBoundary),
    ("rejects incomplete transported recursive group ownership", testIncompleteRecursiveGroupOwnership),
    ("orders same-statement recursion before rebinding and descendants", testSameStatementFailureKindOrder),
    ("binds a later callable rebinding to the nearest prior declaration", testCanonicalCallableRebindingDependencies "later-callable-rebinding-calls-nearest-prior"),
    ("trusts canonical ownership across an intervening scalar declaration", testInterveningScalarCanonicalOwnership "intervening-scalar-canonical-ownership"),
    ("trusts canonical ownership across multiple scalar shadows", testInterveningScalarCanonicalOwnership "multiple-intervening-scalars-canonical-ownership"),
    ("trusts canonical ownership across callable and scalar shadows", testInterveningScalarCanonicalOwnership "interleaved-callable-scalar-canonical-ownership"),
    ("retains every established canonical recursion owner exactly once", testCanonicalRecursionTransportControls),
    ("resolves a nested alias to its nearest prior outer declaration", testNestedPriorOuterAliasOwnership "nested-prior-outer-alias-mutual-recursion"),
    ("resolves a nested conditional alias to its nearest prior outer declaration", testNestedPriorOuterAliasOwnership "nested-prior-outer-conditional-alias-mutual-recursion"),
    ("keeps a nested self-recursive lambda local to its block", testNestedSelfRecursiveLambdaOwnership),
    ("rejects direct recursion that escapes through a nested lambda", testNestedLambdaRecursiveAdmission),
    ("classifies an accepted then rejected callable rebinding", testRejectedCallableRebinding "accepted-then-rejected-callable-rebinding"),
    ("orders rejected callable recursion before rebinding and descendants", testRejectedCallableRebinding "rejected-recursive-callable-rebinding-order"),
    ("classifies a rejected then accepted callable rebinding", testRejectedCallableRebinding "rejected-then-accepted-callable-rebinding"),
    ("classifies repeated rejected callable rebindings", testRejectedCallableRebinding "repeated-rejected-callable-rebinding"),
    ("keeps a prior scalar out of rejected callable rebinding", testRejectedCallableRebinding "scalar-then-rejected-callable-control"),
    ("retains accepted callable ownership across a scalar before rejection", testRejectedCallableRebinding "accepted-scalar-rejected-callable-rebinding"),
    ("retains rejected callable ownership across a scalar before acceptance", testRejectedCallableRebinding "rejected-scalar-accepted-callable-rebinding"),
    ("selects the nearest of three same-name declarations", testCanonicalCallableRebindingDependencies "three-same-name-nearest-prior-mutual-recursion"),
    ("preserves canonical self recursion when no prior binding exists", testCanonicalCallableRebindingDependencies "canonical-self-recursion-no-prior"),
    ("preserves canonical mutual recursion between peers", testCanonicalCallableRebindingDependencies "canonical-mutual-recursion-peers"),
    ("keeps nearest-rebinding mutual references acyclic", testCanonicalCallableRebindingDependencies "nearest-rebinding-mutual-control"),
    ("keeps callable rebinding parameter shadows out of recursion", testCanonicalCallableRebindingDependencies "rebinding-parameter-shadow-control"),
    ("keeps callable rebinding local shadows out of recursion", testCanonicalCallableRebindingDependencies "rebinding-local-shadow-control"),
    ("preserves rejected self-alias declarations before profile acceptance", testRejectedCallableDeclarationTransport "rejected-self-alias-recursion"),
    ("preserves rejected mutual-alias declarations before profile acceptance", testRejectedCallableDeclarationTransport "rejected-mutual-alias-recursion"),
    ("preserves rejected conditional-root declarations before profile acceptance", testRejectedCallableDeclarationTransport "rejected-alias-conditional-mutual-recursion"),
    ("preserves rejected operator-alias declarations before profile acceptance", testRejectedCallableDeclarationTransport "rejected-operator-alias-self-recursion"),
    ("keeps eager operator conditions out of alias-only recursion", testRejectedCallableDeclarationTransport "rejected-eager-operator-conditional-control"),
    ("keeps rejected callable parameter shadows out of declaration cycles", testRejectedCallableDeclarationTransport "rejected-alias-parameter-shadow-control"),
    ("keeps rejected callable local shadows out of declaration cycles", testRejectedCallableDeclarationTransport "rejected-alias-local-shadow-control"),
    ("keeps eager self use outside an unrelated callable result", testRejectedCallableDeclarationTransport "rejected-eager-self-before-callable-result-control"),
    ("preserves nearest-prior callable ownership through a block alias rebinding", testRejectedCallableDeclarationTransport "rejected-block-nearest-prior-callable-rebinding-recursion"),
    ("preserves recursion dependencies through rejected producer trees", testRejectedProducerDependencyTransport),
    ("maps non-builtin operator forms and excludes builtins", testOperatorDependencyNames),
    ("diagnostics take precedence over profile failures", testDiagnosticPrecedence),
    ("reports the initial input profile failures", testInputFailures),
    ("ranks every input failure before resolved-module failures", testInputModuleFailureOrder),
    ("reports every additional foundation profile failure", testAdditionalProfileFailures)
  ]
