#!/usr/bin/env python3
"""Guard the trusted-source publication boundary for the Jazz website.

This checker enforces a small set of repository conventions and scans generated
resource contexts. It deliberately does not interpret TypeScript, JSX, MDX, or
arbitrary expressions; the repository's authored source is trusted code.
"""

from __future__ import annotations

import os
import json
import re
import sys
from html import unescape
from html.parser import HTMLParser
from pathlib import Path
from urllib.parse import urlsplit


CONFIG = "website/docusaurus.config.ts"
PRODUCTION_ORIGIN = "https://un3qual.github.io"
PRODUCTION_BASE = "/jazz/"
GITHUB_NAVIGATION = {
    "https://github.com/un3qual/jazz",
    "https://github.com/un3qual/jazz/issues",
    "https://github.com/un3qual/jazz/security/policy",
    "https://github.com/un3qual/jazz/blob/main/LICENSE",
}
FORBIDDEN_REFERENCES = (
    ".codex",
    "docs/execution",
    "docs/superpowers",
    "jazz-hs",
    "jazz-next",
    "jazz2",
    "jazznext",
    "rfcs",
)
FACTORIAL_SOURCE = "examples/functions/factorial.jz"
FACTORIAL_GENERATED = "website/src/generated/factorial.ts"
FACTORIAL_HEADER = (
    "// Generated by website/scripts/sync-factorial.mjs. Do not edit.\n"
)
AUTHORED_SUFFIXES = {
    ".cjs",
    ".css",
    ".html",
    ".js",
    ".jsx",
    ".md",
    ".mdx",
    ".mjs",
    ".svg",
    ".ts",
    ".tsx",
}
REMOTE_REFERENCE = re.compile(
    r"(?:[A-Za-z][A-Za-z0-9+.-]*:)?//[^\s\"'`<>(){}\[\]]+"
)
CSS_URL = re.compile(
    r"url\(\s*(?P<quote>['\"]?)(?P<target>.*?)(?P=quote)\s*\)", re.IGNORECASE
)
CSS_IMPORT = re.compile(
    r"@import\s+(?!url\()(?P<quote>['\"])(?P<target>.*?)(?P=quote)",
    re.IGNORECASE,
)


def label(root: Path, path: Path) -> str:
    try:
        return path.relative_to(root).as_posix()
    except ValueError:
        return str(path)


def read_text(root: Path, path: Path, violations: list[str]) -> str | None:
    try:
        return path.read_text(encoding="utf-8")
    except (OSError, UnicodeError) as error:
        violations.append(f"{label(root, path)}: cannot read UTF-8 text: {error}")
        return None


def literal_values(source: str, property_name: str) -> list[str]:
    pattern = re.compile(
        rf"\b{re.escape(property_name)}\s*:\s*(['\"])(.*?)\1",
    )
    return [match.group(2) for match in pattern.finditer(source)]


def check_config(root: Path, violations: list[str]) -> None:
    path = root / CONFIG
    if not path.is_file():
        violations.append(f"{CONFIG}: required Docusaurus configuration is missing")
        return
    source = read_text(root, path, violations)
    if source is None:
        return

    canonical_declaration = re.findall(
        r"^const config: Config\s*=\s*\{", source, re.MULTILINE
    )
    canonical_export = re.findall(r"^export default config;\s*$", source, re.MULTILINE)
    if (
        len(canonical_declaration) != 1
        or len(canonical_export) != 1
        or re.search(r"export default config;\s*\Z", source) is None
    ):
        violations.append(
            f"{CONFIG}: use canonical `const config: Config` and `export default config` shape"
        )

    requirements = (
        ("url", [PRODUCTION_ORIGIN], f"production url must be exactly {PRODUCTION_ORIGIN}"),
        ("baseUrl", [PRODUCTION_BASE], f"production baseUrl must be exactly {PRODUCTION_BASE}"),
        ("onBrokenLinks", ["throw"], "broken links must throw"),
        ("format", ["md"], "markdown format must be exactly md"),
        ("onBrokenMarkdownLinks", ["throw"], "broken Markdown links must throw"),
        ("path", ["../docs"], "docs path must be exactly ../docs"),
        ("routeBasePath", ["docs"], "docs routeBasePath must be exactly docs"),
    )
    for property_name, expected, message in requirements:
        if literal_values(source, property_name) != expected:
            violations.append(f"{CONFIG}: {message}")
    if re.findall(r"^\s*blog\s*:\s*([^,\n]+)", source, re.MULTILINE) != ["false"]:
        violations.append(f"{CONFIG}: blog must be disabled")


def public_doc_entries(docs: Path) -> list[Path]:
    entries: list[Path] = []
    for directory, directory_names, file_names in os.walk(docs, followlinks=False):
        directory_names.sort()
        file_names.sort()
        current = Path(directory)
        entries.extend(current / name for name in directory_names)
        entries.extend(current / name for name in file_names)
    return sorted(entries, key=lambda path: path.as_posix())


def check_public_docs(root: Path, violations: list[str]) -> None:
    docs = root / "docs"
    if not docs.is_dir():
        violations.append("docs: configured public documentation directory is missing")
        return
    boundary = docs.resolve()
    for path in public_doc_entries(docs):
        path_label = label(root, path)
        if path.is_symlink():
            if not path.resolve().is_relative_to(boundary):
                violations.append(
                    f"{path_label}: public documentation symlink escapes docs"
                )
            continue
        if path.is_file() and path.suffix != ".md":
            violations.append(
                f"{path_label}: public docs regular files must use the .md extension; "
                "move site assets to website/static"
            )


def check_generated_factorial(root: Path, violations: list[str]) -> None:
    source_path = root / FACTORIAL_SOURCE
    generated_path = root / FACTORIAL_GENERATED
    source = read_text(root, source_path, violations)
    generated = read_text(root, generated_path, violations)
    if source is None or generated is None:
        return
    expected = (
        FACTORIAL_HEADER
        + f"export const factorialSource = {json.dumps(source, ensure_ascii=False)};\n"
    )
    if generated != expected:
        violations.append(
            f"{FACTORIAL_GENERATED}: generated factorial source does not match "
            f"{FACTORIAL_SOURCE} byte-for-byte"
        )


def authored_paths(root: Path) -> list[Path]:
    paths = [root / CONFIG, root / "website/sidebars.ts"]
    for source_root in (
        root / "website/src",
        root / "website/scripts",
        root / "website/static",
    ):
        if not source_root.exists():
            continue
        for directory, directory_names, file_names in os.walk(
            source_root, followlinks=False
        ):
            directory_names.sort()
            for name in sorted(file_names):
                path = Path(directory) / name
                if path.suffix.casefold() in AUTHORED_SUFFIXES:
                    paths.append(path)
    return sorted(set(paths), key=lambda path: path.as_posix())


def allowed_authored_remote(url: str) -> bool:
    return (
        url == "http://www.w3.org/2000/svg"
        or url == PRODUCTION_ORIGIN
        or url.startswith(f"{PRODUCTION_ORIGIN}{PRODUCTION_BASE}")
        or url in GITHUB_NAVIGATION
    )


def check_authored_sources(root: Path, violations: list[str]) -> None:
    website = root / "website"
    if not website.is_dir():
        violations.append("website: required website directory is missing")
        return
    for path in authored_paths(root):
        if not path.is_file():
            continue
        source = read_text(root, path, violations)
        if source is None:
            continue
        path_label = label(root, path)
        folded = source.casefold()
        folded_path = path_label.casefold()
        for forbidden in FORBIDDEN_REFERENCES:
            if forbidden in folded or forbidden in folded_path:
                violations.append(
                    f"{path_label}: forbidden publication reference: {forbidden}"
                )
        if any(
            not allowed_authored_remote(match.group())
            for match in REMOTE_REFERENCE.finditer(source)
        ):
            violations.append(
                f"{path_label}: remote authored reference is not allowlisted"
            )


def remote_resource(target: str) -> bool:
    value = unescape(target.strip())
    parsed = urlsplit(value)
    return value.startswith("//") or (
        bool(parsed.scheme) and parsed.scheme.casefold() not in {"data", "blob", "mailto"}
    )


def allowed_generated_navigation(target: str) -> bool:
    value = unescape(target.strip())
    return value in GITHUB_NAVIGATION or value.startswith(
        f"{PRODUCTION_ORIGIN}{PRODUCTION_BASE}"
    )


class ResourceParser(HTMLParser):
    """Collect remote fetches while allowing known static-site navigation metadata."""

    def __init__(self) -> None:
        super().__init__(convert_charrefs=True)
        self.remote_fetch = False

    def handle_starttag(
        self, tag: str, attrs: list[tuple[str, str | None]]
    ) -> None:
        attributes = {name.casefold(): value or "" for name, value in attrs}
        for name in (
            "src",
            "poster",
            "background",
            "data",
            "action",
            "formaction",
            "manifest",
        ):
            target = attributes.get(name)
            if target and remote_resource(target):
                self.remote_fetch = True
        for name in ("srcset", "imagesrcset"):
            candidates = attributes.get(name, "")
            targets = [
                candidate.strip().split()[0]
                for candidate in candidates.split(",")
                if candidate.strip()
            ]
            if any(remote_resource(target) for target in targets):
                self.remote_fetch = True
        target = attributes.get("href")
        if not target or not remote_resource(target):
            return
        rel = set(attributes.get("rel", "").casefold().split())
        navigation = tag.casefold() in {"a", "area"}
        metadata = tag.casefold() == "link" and bool(rel & {"canonical", "alternate"})
        if not ((navigation or metadata) and allowed_generated_navigation(target)):
            self.remote_fetch = True


def css_targets(source: str) -> list[str]:
    without_comments = re.sub(r"/\*.*?\*/", "", source, flags=re.DOTALL)
    targets = [match.group("target") for match in CSS_URL.finditer(without_comments)]
    targets.extend(match.group("target") for match in CSS_IMPORT.finditer(without_comments))
    return targets


def check_generated_output(root: Path, violations: list[str]) -> None:
    build = root / "website/build"
    if not build.exists():
        return
    if not build.is_dir() or build.is_symlink():
        violations.append("website/build: generated output must be a real directory")
        return
    for directory, directory_names, file_names in os.walk(build, followlinks=False):
        directory_names.sort()
        for name in sorted(file_names):
            path = Path(directory) / name
            path_label = label(root, path)
            try:
                contents = path.read_bytes()
            except OSError as error:
                violations.append(f"{path_label}: cannot read generated output: {error}")
                continue
            folded = contents.lower()
            for forbidden in FORBIDDEN_REFERENCES:
                if forbidden.encode().lower() in folded:
                    violations.append(
                        f"{path_label}: generated output contains forbidden string: {forbidden}"
                    )
            if path.suffix.casefold() not in {".css", ".html"}:
                continue
            source = contents.decode("utf-8", errors="replace")
            if path.suffix.casefold() == ".css":
                remote = any(remote_resource(target) for target in css_targets(source))
            else:
                parser = ResourceParser()
                parser.feed(source)
                remote = parser.remote_fetch
            if remote:
                violations.append(
                    f"{path_label}: generated output loads a remote resource"
                )


def main(argv: list[str]) -> int:
    if len(argv) > 2:
        print("usage: check-website-boundary.py [repository-root]")
        return 2
    root = (
        Path(argv[1]).expanduser().resolve()
        if len(argv) == 2
        else Path(__file__).resolve().parent.parent
    )
    violations: list[str] = []
    if not root.is_dir():
        violations.append(f"{root}: repository root is not a directory")
    else:
        check_config(root, violations)
        check_public_docs(root, violations)
        check_generated_factorial(root, violations)
        check_authored_sources(root, violations)
        check_generated_output(root, violations)
    if violations:
        print("Website boundary checks failed:")
        for violation in sorted(set(violations)):
            print(f"- {violation}")
        return 1
    print("Website boundary checks passed.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
