#!/usr/bin/env python3
"""Guard the trusted-source publication boundary for the Jazz website.

This checker enforces a small set of repository conventions and scans generated
resource contexts. It deliberately does not interpret TypeScript, JSX, MDX, or
arbitrary expressions; the repository's authored source is trusted code.
"""

from __future__ import annotations

import json
import os
import re
import sys
from html import unescape
from html.parser import HTMLParser
from pathlib import Path
from urllib.parse import urlsplit


CONFIG = "website/docusaurus.config.ts"
PRODUCTION_ORIGIN = "https://un3qual.github.io"
PRODUCTION_BASE = "/jazz/"
GITHUB_NAVIGATION = {
    "https://github.com/un3qual/jazz",
    "https://github.com/un3qual/jazz/issues",
    "https://github.com/un3qual/jazz/security/policy",
    "https://github.com/un3qual/jazz/blob/main/LICENSE",
    "https://github.com/un3qual/jazz/blob/main/CONTRIBUTING.md",
}
FORBIDDEN_REFERENCES = (
    ".codex",
    "docs/execution",
    "docs/superpowers",
    "jazz-hs",
    "jazz-next",
    "jazz2",
    "jazznext",
    "rfcs",
)
FACTORIAL_SOURCE = "examples/functions/factorial.jz"
FACTORIAL_CASES = "scripts/example-cases.tsv"
FACTORIAL_GENERATED = "website/src/generated/factorial.ts"
FACTORIAL_HEADER = (
    "// Generated by website/scripts/sync-factorial.mjs. Do not edit.\n"
)
AUTHORED_SUFFIXES = {
    ".cjs",
    ".css",
    ".html",
    ".js",
    ".jsx",
    ".md",
    ".mdx",
    ".mjs",
    ".svg",
    ".ts",
    ".tsx",
}
REMOTE_REFERENCE = re.compile(
    r"(?:"
    r"[A-Za-z][A-Za-z0-9+.-]*://[^\s\"'`<>(){}\[\]]+"
    r"|//(?:[A-Za-z0-9-]+\.)+[A-Za-z0-9-]+[^\s\"'`<>(){}\[\]]*"
    r")"
)
CSS_IMPORT = re.compile(
    r"@import\s+(?!url\()(?P<quote>['\"])(?P<target>.*?)(?P=quote)",
    re.IGNORECASE,
)
CSS_ESCAPE = re.compile(
    r"\\(?:"
    r"(?P<hex>[0-9A-Fa-f]{1,6})(?:[ \t\r\n\f])?"
    r"|(?P<newline>\r\n|[\r\n\f])"
    r"|(?P<char>.)"
    r")",
    re.DOTALL,
)
SVG_URL_PRESENTATION_ATTRIBUTES = (
    "clip-path",
    "cursor",
    "fill",
    "filter",
    "marker",
    "marker-start",
    "marker-mid",
    "marker-end",
    "mask",
    "stroke",
)


def label(root: Path, path: Path) -> str:
    try:
        return path.relative_to(root).as_posix()
    except ValueError:
        return str(path)


def read_text(root: Path, path: Path, violations: list[str]) -> str | None:
    try:
        return path.read_text(encoding="utf-8")
    except (OSError, UnicodeError) as error:
        violations.append(f"{label(root, path)}: cannot read UTF-8 text: {error}")
        return None


def literal_values(source: str, property_name: str) -> list[str]:
    pattern = re.compile(
        rf"\b{re.escape(property_name)}\s*:\s*(['\"])(.*?)\1",
    )
    return [match.group(2) for match in pattern.finditer(source)]


def check_config(root: Path, violations: list[str]) -> None:
    path = root / CONFIG
    if not path.is_file():
        violations.append(f"{CONFIG}: required Docusaurus configuration is missing")
        return
    source = read_text(root, path, violations)
    if source is None:
        return

    canonical_declaration = re.findall(
        r"^const config: Config\s*=\s*\{", source, re.MULTILINE
    )
    canonical_export = re.findall(r"^export default config;\s*$", source, re.MULTILINE)
    if (
        len(canonical_declaration) != 1
        or len(canonical_export) != 1
        or re.search(r"export default config;\s*\Z", source) is None
    ):
        violations.append(
            f"{CONFIG}: use canonical `const config: Config` and `export default config` shape"
        )

    requirements = (
        ("url", [PRODUCTION_ORIGIN], f"production url must be exactly {PRODUCTION_ORIGIN}"),
        ("baseUrl", [PRODUCTION_BASE], f"production baseUrl must be exactly {PRODUCTION_BASE}"),
        ("onBrokenLinks", ["throw"], "broken links must throw"),
        ("format", ["md"], "markdown format must be exactly md"),
        ("onBrokenMarkdownLinks", ["throw"], "broken Markdown links must throw"),
        ("path", ["../docs"], "docs path must be exactly ../docs"),
        ("routeBasePath", ["docs"], "docs routeBasePath must be exactly docs"),
    )
    for property_name, expected, message in requirements:
        if literal_values(source, property_name) != expected:
            violations.append(f"{CONFIG}: {message}")
    if re.findall(r"^\s*blog\s*:\s*([^,\n]+)", source, re.MULTILINE) != ["false"]:
        violations.append(f"{CONFIG}: blog must be disabled")


def public_doc_entries(docs: Path) -> list[Path]:
    entries: list[Path] = []
    for directory, directory_names, file_names in os.walk(docs, followlinks=False):
        directory_names.sort()
        file_names.sort()
        current = Path(directory)
        entries.extend(current / name for name in directory_names)
        entries.extend(current / name for name in file_names)
    return sorted(entries, key=lambda path: path.as_posix())


def check_public_docs(root: Path, violations: list[str]) -> None:
    docs = root / "docs"
    if not docs.is_dir() or docs.is_symlink():
        violations.append(
            "docs: configured public documentation directory must be a real directory"
        )
        return
    boundary = docs.resolve()
    for path in public_doc_entries(docs):
        path_label = label(root, path)
        if path.is_file() and path.suffix != ".md":
            violations.append(
                f"{path_label}: public docs files must use the .md extension; "
                "move site assets to website/static"
            )
        if path.is_symlink():
            if not path.resolve().is_relative_to(boundary):
                violations.append(
                    f"{path_label}: public documentation symlink escapes docs"
                )
            continue


def factorial_case(cases: str) -> tuple[str, str, str] | None:
    lines = cases.splitlines()
    header = "name\tsources\texpected\targs"
    factorial_cases = [
        fields
        for line in lines[1:]
        if line
        and len(fields := line.split("\t")) == 4
        and fields[0] == "factorial"
    ]
    if not lines or lines[0] != header or len(factorial_cases) != 1:
        return None
    _, raw_sources, expected_output, args = factorial_cases[0]
    return raw_sources, expected_output, args


def factorial_invocation(source: str) -> str | None:
    source_lines = source.rstrip().splitlines()
    if (
        not source_lines
        or not source_lines[-1].strip().endswith(".")
        or source_lines[-1].strip() == "."
    ):
        return None
    return source_lines[-1].strip()[:-1].strip()


def generated_factorial_module(source: str, invocation: str, output: str) -> str:
    return (
        FACTORIAL_HEADER
        + f"export const factorialSource = {json.dumps(source, ensure_ascii=False)};\n"
        + "export const factorialInvocation = "
        + f"{json.dumps(invocation, ensure_ascii=False)};\n"
        + "export const factorialExpectedOutput = "
        + f"{json.dumps(output, ensure_ascii=False)};\n"
    )


def check_generated_factorial(root: Path, violations: list[str]) -> None:
    source = read_text(root, root / FACTORIAL_SOURCE, violations)
    cases = read_text(root, root / FACTORIAL_CASES, violations)
    generated = read_text(root, root / FACTORIAL_GENERATED, violations)
    if source is None or cases is None or generated is None:
        return

    case = factorial_case(cases)
    if case is None:
        violations.append(
            f"{FACTORIAL_CASES}: must contain exactly one valid factorial case"
        )
        return
    raw_sources, expected_output, args = case
    if (
        FACTORIAL_SOURCE not in raw_sources.split(",")
        or args != f"--run {FACTORIAL_SOURCE}"
        or not expected_output
    ):
        violations.append(
            f"{FACTORIAL_CASES}: factorial case must execute {FACTORIAL_SOURCE}"
        )
        return
    invocation = factorial_invocation(source)
    if invocation is None:
        violations.append(f"{FACTORIAL_SOURCE}: must end with the displayed invocation")
        return

    expected = generated_factorial_module(source, invocation, expected_output)
    if generated != expected:
        violations.append(
            f"{FACTORIAL_GENERATED}: generated factorial source does not match "
            "the compiler-backed factorial case"
        )


def authored_paths(root: Path) -> list[Path]:
    paths = [root / CONFIG, root / "website/sidebars.ts"]
    for source_root in (
        root / "website/src",
        root / "website/scripts",
        root / "website/static",
    ):
        if not source_root.exists():
            continue
        for directory, directory_names, file_names in os.walk(
            source_root, followlinks=False
        ):
            directory_names.sort()
            for name in sorted(file_names):
                path = Path(directory) / name
                if path.suffix.casefold() in AUTHORED_SUFFIXES:
                    paths.append(path)
    return sorted(set(paths), key=lambda path: path.as_posix())


def allowed_authored_remote(url: str) -> bool:
    return (
        url == "http://www.w3.org/2000/svg"
        or url == PRODUCTION_ORIGIN
        or url.startswith(f"{PRODUCTION_ORIGIN}{PRODUCTION_BASE}")
        or url in GITHUB_NAVIGATION
    )


def check_authored_sources(root: Path, violations: list[str]) -> None:
    website = root / "website"
    if not website.is_dir():
        violations.append("website: required website directory is missing")
        return
    for path in authored_paths(root):
        if not path.is_file():
            continue
        source = read_text(root, path, violations)
        if source is None:
            continue
        path_label = label(root, path)
        folded = source.casefold()
        folded_path = path_label.casefold()
        for forbidden in FORBIDDEN_REFERENCES:
            if forbidden in folded or forbidden in folded_path:
                violations.append(
                    f"{path_label}: forbidden publication reference: {forbidden}"
                )
        for match in REMOTE_REFERENCE.finditer(source):
            if not allowed_authored_remote(match.group()):
                violations.append(
                    f"{path_label}: remote authored reference is not allowlisted: "
                    f"{match.group()}"
                )


def remote_resource(target: str) -> bool:
    value = unescape(target.strip()).replace("\\", "/")
    try:
        parsed = urlsplit(value)
    except ValueError:
        return True
    return bool(parsed.netloc) or value.startswith("//") or (
        bool(parsed.scheme) and parsed.scheme.casefold() not in {"data", "blob", "mailto"}
    )


def allowed_generated_navigation(target: str) -> bool:
    value = unescape(target.strip())
    return value in GITHUB_NAVIGATION or value.startswith(
        f"{PRODUCTION_ORIGIN}{PRODUCTION_BASE}"
    )


class ResourceParser(HTMLParser):
    """Collect remote fetches while allowing known static-site navigation metadata."""

    def __init__(self) -> None:
        """Initialize generated-document resource state."""
        super().__init__(convert_charrefs=True)
        self.remote_fetch = False
        self.in_style = False
        self.embedded_documents: list[str] = []

    @staticmethod
    def attribute_values(
        attrs: list[tuple[str, str | None]],
    ) -> dict[str, list[str]]:
        attribute_values: dict[str, list[str]] = {}
        for name, value in attrs:
            attribute_values.setdefault(name.casefold(), []).append(value or "")
        return attribute_values

    def collect_embedded_documents(
        self, attribute_values: dict[str, list[str]],
    ) -> None:
        self.embedded_documents.extend(
            source for source in attribute_values.get("srcdoc", []) if source
        )

    def scan_url_attributes(
        self, attribute_values: dict[str, list[str]],
    ) -> None:
        for name in (
            "src",
            "poster",
            "background",
            "data",
            "action",
            "formaction",
            "manifest",
            "xlink:href",
        ):
            targets = attribute_values.get(name, [])
            if any(target and remote_resource(target) for target in targets):
                self.remote_fetch = True

    def scan_srcset_attributes(
        self, attribute_values: dict[str, list[str]],
    ) -> None:
        for name in ("srcset", "imagesrcset"):
            targets = [
                candidate.strip().split()[0]
                for candidates in attribute_values.get(name, [])
                for candidate in candidates.split(",")
                if candidate.strip()
            ]
            if any(remote_resource(target) for target in targets):
                self.remote_fetch = True

    def scan_inline_styles(
        self, attribute_values: dict[str, list[str]],
    ) -> None:
        for source in attribute_values.get("style", []):
            if any(remote_resource(target) for target in css_targets(source)):
                self.remote_fetch = True

    def scan_svg_presentation_attributes(
        self, attribute_values: dict[str, list[str]],
    ) -> None:
        for name in SVG_URL_PRESENTATION_ATTRIBUTES:
            for source in attribute_values.get(name, []):
                if any(remote_resource(target) for target in css_targets(source)):
                    self.remote_fetch = True

    def scan_href_policy(
        self, tag: str, attribute_values: dict[str, list[str]],
    ) -> None:
        attributes = {
            name: values[0] for name, values in attribute_values.items()
        }
        rel = set(attributes.get("rel", "").casefold().split())
        navigation = tag in {"a", "area"}
        metadata = tag == "link" and bool(rel & {"canonical", "alternate"})
        for target in attribute_values.get("href", []):
            if remote_resource(target) and not (
                (navigation or metadata) and allowed_generated_navigation(target)
            ):
                self.remote_fetch = True

    def handle_starttag(
        self, tag: str, attrs: list[tuple[str, str | None]]
    ) -> None:
        folded_tag = tag.casefold()
        if folded_tag == "style":
            self.in_style = True
        attribute_values = self.attribute_values(attrs)
        self.collect_embedded_documents(attribute_values)
        self.scan_url_attributes(attribute_values)
        self.scan_srcset_attributes(attribute_values)
        self.scan_inline_styles(attribute_values)
        self.scan_svg_presentation_attributes(attribute_values)
        self.scan_href_policy(folded_tag, attribute_values)

    def handle_endtag(self, tag: str) -> None:
        if tag.casefold() == "style":
            self.in_style = False

    def handle_data(self, data: str) -> None:
        if self.in_style and any(
            remote_resource(target) for target in css_targets(data)
        ):
            self.remote_fetch = True


def decode_css_escapes(value: str) -> str:
    def replace_escape(match: re.Match[str]) -> str:
        if match.group("newline") is not None:
            return ""
        if match.group("char") is not None:
            return match.group("char")
        codepoint = int(match.group("hex"), 16)
        if codepoint == 0 or codepoint > 0x10FFFF or 0xD800 <= codepoint <= 0xDFFF:
            return "\N{REPLACEMENT CHARACTER}"
        return chr(codepoint)

    return CSS_ESCAPE.sub(replace_escape, value)


def css_string_end(source: str, start: int) -> int:
    quote = source[start]
    index = start + 1
    while index < len(source) and source[index] != quote:
        index += 2 if source[index] == "\\" else 1
    return min(index + 1, len(source))


def css_function_end(source: str, body_start: int) -> int | None:
    index = body_start
    depth = 1
    while index < len(source):
        character = source[index]
        if character in "'\"":
            index = css_string_end(source, index)
            continue
        if character == "(":
            depth += 1
        elif character == ")":
            depth -= 1
            if depth == 0:
                return index
        index += 1
    return None


def css_function_calls(source: str) -> list[tuple[str, str]]:
    calls: list[tuple[str, str]] = []
    index = 0
    while index < len(source):
        if source[index] in "'\"":
            index = css_string_end(source, index)
            continue
        if not (source[index].isalpha() or source[index] in "_-"):
            index += 1
            continue
        name_start = index
        while index < len(source) and (
            source[index].isalnum() or source[index] in "_-\\"
        ):
            index += 1
        name = source[name_start:index]
        while index < len(source) and source[index].isspace():
            index += 1
        if index >= len(source) or source[index] != "(":
            continue
        body_start = index + 1
        body_end = css_function_end(source, body_start)
        if body_end is None:
            break
        calls.append(
            (decode_css_escapes(name).casefold(), source[body_start:body_end])
        )
        index = body_start
    return calls


def css_string_values(source: str) -> list[str]:
    values: list[str] = []
    index = 0
    while index < len(source):
        if source[index] not in "'\"":
            index += 1
            continue
        end = css_string_end(source, index)
        values.append(decode_css_escapes(source[index + 1 : end - 1]))
        index = end
    return values


def css_targets(source: str) -> list[str]:
    without_comments = re.sub(r"/\*.*?\*/", "", source, flags=re.DOTALL)
    targets: list[str] = []
    for name, body in css_function_calls(without_comments):
        if name == "url":
            strings = css_string_values(body)
            raw_target = strings[0] if strings else decode_css_escapes(body.strip())
            if raw_target:
                targets.append(raw_target)
        elif name in {"image-set", "-webkit-image-set"}:
            targets.extend(css_string_values(body))
    targets.extend(
        decode_css_escapes(match.group("target"))
        for match in CSS_IMPORT.finditer(without_comments)
    )
    return targets


def html_loads_remote_resource(source: str) -> bool:
    pending = [source]
    parsed: set[str] = set()
    while pending:
        document = pending.pop()
        if document in parsed:
            continue
        parsed.add(document)
        parser = ResourceParser()
        parser.feed(document)
        parser.close()
        if parser.remote_fetch:
            return True
        pending.extend(parser.embedded_documents)
    return False


def check_generated_file(root: Path, path: Path, violations: list[str]) -> None:
    path_label = label(root, path)
    try:
        contents = path.read_bytes()
    except OSError as error:
        violations.append(f"{path_label}: cannot read generated output: {error}")
        return

    folded = contents.lower()
    for forbidden in FORBIDDEN_REFERENCES:
        if forbidden.encode().lower() in folded:
            violations.append(
                f"{path_label}: generated output contains forbidden string: {forbidden}"
            )
    suffix = path.suffix.casefold()
    if suffix not in {".css", ".html"}:
        return
    source = contents.decode("utf-8", errors="replace")
    remote = (
        any(remote_resource(target) for target in css_targets(source))
        if suffix == ".css"
        else html_loads_remote_resource(source)
    )
    if remote:
        violations.append(f"{path_label}: generated output loads a remote resource")


def check_generated_output(root: Path, violations: list[str]) -> None:
    build = root / "website/build"
    if not build.exists():
        return
    if not build.is_dir() or build.is_symlink():
        violations.append("website/build: generated output must be a real directory")
        return
    for directory, directory_names, file_names in os.walk(build, followlinks=False):
        directory_names.sort()
        for name in sorted(file_names):
            check_generated_file(root, Path(directory) / name, violations)


def main(argv: list[str]) -> int:
    if len(argv) > 2:
        print("usage: check-website-boundary.py [repository-root]")
        return 2
    root = (
        Path(argv[1]).expanduser().resolve()
        if len(argv) == 2
        else Path(__file__).resolve().parent.parent
    )
    violations: list[str] = []
    if not root.is_dir():
        violations.append(f"{root}: repository root is not a directory")
    else:
        check_config(root, violations)
        check_public_docs(root, violations)
        check_generated_factorial(root, violations)
        check_authored_sources(root, violations)
        check_generated_output(root, violations)
    if violations:
        print("Website boundary checks failed:")
        for violation in sorted(set(violations)):
            print(f"- {violation}")
        return 1
    print("Website boundary checks passed.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
