name:                jazz
version:             0.1.0.0
github:              "un3qual/jazz"
license:             MIT
author:              "Ryan Ramsdell"
maintainer:          "example@example.com"
copyright:           "2024 Ryan Ramsdell"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/jazz#readme>

dependencies:
- base >= 4.7 && < 5
- megaparsec
- text
- containers
- parser-combinators
- process
- file-embed
- string-conversions
- directory
- unix
- diagnose
- haskeline
- prettyprinter
- prettyprinter-ansi-terminal
- pretty-show
- tasty
- tasty-hunit
- tasty-hspec
- hspec
- string-qq
- mtl
- pretty
- time
- lens
- criterion
- bifunctors

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  jazz-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - jazz

tests:
  jazz-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - jazz
